export const SET_ENERGY_THRESHOLD="SET_ENERGY_THRESHOLD";
export const UPDATE_ENERGY_USAGE="UPDATE_ENERGY_USAGE";

export const SET_KITCHEN_TEMPERATURE="SET_KITCHEN_TEMPERATURE";
export const SET_BEDROOM_TEMPERATURE="SET_BEDROOM_TEMPERATURE";
export const SET_LIVINGROOM_TEMPERATURE="SET_LIVINGROOM_TEMPERATURE";
export const SET_BATHROOM_TEMPERATURE="SET_BATHROOM_TEMPERATURE";

export const CHANGE_KITCHEN_TEMPERATURE="CHANGE_KITCHEN_TEMPERATURE";
export const CHANGE_BEDROOM_TEMPERATURE="CHANGE_BEDROOM_TEMPERATURE";
export const CHANGE_BATHROOM_TEMPERATURE="CHANGE_BATHROOM_TEMPERATURE";
export const CHANGE_LIVINGROOM_TEMPERATURE="CHANGE_LIVINGROOM_TEMPERATURE";

export const  SET_BEDROOM_STATUS="SET_BEDROOM_STATUS";
export const  SET_BATHROOM_STATUS="SET_BATHROOM_STATUS";
export const  SET_LIVINGROOM_STATUS="SET_LIVINGROOM_STATUS";
export const  SET_KITCHEN_STATUS="SET_KITCHEN_STATUS";

export const SET_KITCHEN_TEMP_DATA="SET_KITCHEN_TEMP_DATA";
export const SET_LIVINGROOM_TEMP_DATA="SET_LIVINGROOM_TEMP_DATA";
export const SET_BEDROOM_TEMP_DATA="SET_BEDROOM_TEMP_DATA";
export const SET_BATHROOM_TEMP_DATA="SET_BATHROOM_TEMP_DATA";


